version: '3'

services:
  php:
    container_name: php-practice
    build: ./docker/php
    volumes:
    - ./server:/var/www

  react_node:
    container_name: react-practice
    build: ./docker/react
    environment:
      - NODE_ENV=development
    volumes:
    - ./front:/usr/src/app
    command: sh -c "cd reactapp; docker exec -it react-practice /bin/bash; yarn start"
    ports:
    - "3000:3000"

  nginx:
    image: nginx
    container_name: nginx-practice
    ports:
    - 80:80
    volumes:
    - ./server:/var/www
    - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
    - php

  db:
    image: mysql:8.0.14
    container_name: db-host-practice
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_USER: root
      MYSQL_DATABASE: test_database
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
    - ./docker/db/data:/var/lib/mysql
    - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
    - ./docker/db/sql:/docker-entrypoint-initdb.d
    ports:
    - 3306:3306

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db-host-practice
      - PMA_USER=root
      - PMA_PASSWORD=root
    links:
      - db
    ports:
      - 8080:80
    volumes:
      - /sessions